import { useState } from "react";
import ForthTaskForm from "./ForthTaskForm";

const ForthNewTask = (props) => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const enterTaskHandler = async (taskText) => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch(
        "https://react-costum-components-default-rtdb.firebaseio.com/tasks.json",
        {
          method: "POST",
          headers: {
            "Content-type": "application/json",
          },
          body: JSON.stringify({ text: taskText }),
        }
      );

      if (!response.ok) throw new Error("Request Failed.");

      const data = await response.json();

      const generatedId = data.name;
      // Define the new task with id generated by firebase
      const createdTask = { id: generatedId, text: taskText };

      props.onAddTask(createdTask);
    } catch (error) {
      setError(error.message || "Something is wrong.");
    }
    setIsLoading(false);
  };

  return (
    <div>
      <ForthTaskForm onEnterTask={enterTaskHandler} isLoading={isLoading} />
      {error && <p>{error}</p>}
    </div>
  );
};

export default ForthNewTask;
